### ISSUE TITLE
spm install 时出错，不知道什么问题

### ISSUE THREAD

**Issue by ken1987** [spmjs/spmjs.io#129]
D:\test>spm install zepto
undefined:1
锘縶
^
SyntaxError: Unexpected token 锘?
    at Object.parse (native)
    at me.readFileSync (C:\Users\ken\AppData\Roaming\npm\node_modules\spm\node_m
odules\fs-extra\node_modules\jsonfile\lib\jsonfile.js:31:17)
    at Object.<anonymous> (C:\Users\ken\AppData\Roaming\npm\node_modules\spm\lib
\client.js:10:13)
    at Module._compile (module.js:460:26)
    at Object.gnodeJsExtensionCompiler [as .js] (C:\Users\ken\AppData\Roaming\np
m\node_modules\spm\node_modules\gnode\index.js:61:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\ken\AppData\Roaming\npm\node_modules\spm\bin
\spm-install:7:15)

**Comment by afc163** [comment]
看上去是网络问题，重试也是这样吗？能访问 http://spmjs.io 吗

**Comment by ken1987** [comment]
@afc163 按照新手入门文档中说的来操作的，貌似省略了很多步骤，几个依赖没安装，导致不能运转
