### ISSUE TITLE
部署自己的 spmjs.io 遇到以下问题, 麻烦帮我看下

### ISSUE THREAD

**Issue by alvin2ye** [spmjs/spmjs.io#156]
由于很多包没有更新, 只能自己动手了. 

node 不熟...

```
➜  spmjs.io git:(master) ✗ node app.js
[2015-11-09 17:33:04] [sync] start
Executing (default): CREATE TABLE IF NOT EXISTS `Accounts` (`id` INTEGER, `login` VARCHAR(255) UNIQUE, `avatar_url` VARCHAR(255), `url` VARCHAR(255), `html_url` VARCHAR(255), `name` VARCHAR(255), `company` VARCHAR(255), `blog` VARCHAR(255), `location` VARCHAR(255), `email` VARCHAR(255), `bio` VARCHAR(255), `public_repos` INTEGER, `public_gists` INTEGER, `followers` INTEGER, `following` INTEGER, `authkey` VARCHAR(255), `count` INTEGER, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL);
Executing (default): PRAGMA INDEX_LIST(`Accounts`)
Executing (default): PRAGMA INDEX_INFO(`sqlite_autoindex_Accounts_1`)
Executing (default): CREATE TABLE IF NOT EXISTS `Downloads` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `package` VARCHAR(255), `time` BIGINT, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL);
Executing (default): PRAGMA INDEX_LIST(`Downloads`)
Executing (default): CREATE TABLE IF NOT EXISTS `Histories` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `name` VARCHAR(255), `version` VARCHAR(255), `publisher_name` VARCHAR(255), `publisher_id` INTEGER, `time` BIGINT, `action` VARCHAR(255), `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL);
Executing (default): PRAGMA INDEX_LIST(`Histories`)
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3000
  at Object.exports._errnoException (util.js:860:11)
  at exports._exceptionWithHostPort (util.js:883:20)
  at Server._listen2 (net.js:1234:14)
  at listen (net.js:1270:10)
  at Server.listen (net.js:1366:5)
  at /private/tmp/spmjs.io/app.js:143:26
  at tryCatcher (/private/tmp/spmjs.io/node_modules/sequelize/node_modules/bluebird/js/main/util.js:26:23)
  at Promise._settlePromiseFromHandler (/private/tmp/spmjs.io/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:503:31)
  at Promise._settlePromiseAt (/private/tmp/spmjs.io/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:577:18)
  at Async._drainQueue (/private/tmp/spmjs.io/node_modules/sequelize/node_modules/bluebird/js/main/async.js:128:12)
  at Async._drainQueues (/private/tmp/spmjs.io/node_modules/sequelize/node_modules/bluebird/js/main/async.js:133:10)
  at Immediate.Async.drainQueues [as _onImmediate] (/private/tmp/spmjs.io/node_modules/sequelize/node_modules/bluebird/js/main/async.js:15:14)
  at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by alvin2ye** [comment]
先说明 端口3000 没被占

**Comment by alvin2ye** [comment]
ubuntu 下可以顺利开启.
