### ISSUE TITLE
添加svn后，npm start 运行不了

### ISSUE THREAD

**Issue by kxbrand** [spmjs/spmjs.io#34]
将spmjs.io源文件放入svn(`npm install` 正常)，然后`svn update`后，每个文件夹内都有`.svn`这个文件夹，此时执行命令`npm start`报错如下：

```
/wwwroot/spmjs.io/node_modules/forever/node_modules/utile/lib/index.js:264
        Object.defineProperty(target, attr, {
               ^
TypeError: Cannot redefine property: .svn
    at Function.defineProperty (native)
    at /wwwroot/spmjs.io/node_modules/forever/node_modules/utile/lib/index.js:264:16
    at Array.forEach (native)
    at /wwwroot/spmjs.io/node_modules/forever/node_modules/utile/lib/index.js:256:35
    at Array.forEach (native)
    at Object.utile.mixin (/wwwroot/spmjs.io/node_modules/forever/node_modules/utile/lib/index.js:255:29)
    at Object.<anonymous> (/wwwroot/spmjs.io/node_modules/forever/node_modules/flatiron/lib/flatiron.js:30:36)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

```

用`find -name .svn | xargs rm -rf`将`.svn`文件夹后再次执行命令，应该就能执行成功了，但这样又不好纳入svn了。
执行时能不能把`.svn`过滤掉？

**Comment by liyj144** [comment]
可以参考 [https://github.com/flatiron/utile/issues/23](url), 是forever引用的utile库未忽略.开头的文件和文件夹的原因。
